### ISSUE TITLE
Playlist items with duration but no start time do not stop at the duration time.

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#15]
Here's a test case: https://counterbalance.org/perspevo/pnl5mr-frame.html

Note: the seek bar shows the duration correctly, but the video does not stop when the playhead reaches its end.

**Comment by adrianwyard** [comment]
This seems to work OK on Safari and iOS browsers. So to reproduce use Firefox or Chrome on Desktop OS.

**Comment by adrianwyard** [comment]
This can be worked around by adding a starttime of "00:00" so simply adding that at the conversion stage is a possible fix.

**Comment by kayecandy** [comment]
> This can be worked around by adding a starttime of "00:00" so simply adding that at the conversion stage is a possible fix.

I did something similar, but to the `cndce-counterbalance.js` script instead of the converter. The `starttime` is basically set to `0` if it is undefined

**Comment by adrianwyard** [comment]
Looks good.
