### ISSUE TITLE
The 'title' property is lost in the conversion to JSON

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#17]
I do occasionally set a title in RSS playlists, so those need to be moved over to the JSON versions.

Here's an example of a page with a widget that should show titles below the item thumbnails once they are in the JSON:
https://counterbalance.org/stars-ool/pres-frame.html

**Comment by kayecandy** [comment]
### Just a note 
I generalized the solution for this to all XML properties that the script could detect _(ie. not just the `title` property)_

So for example, if the XML file is like this:
```xml
<item>
   <title>Responses to the Southgate/Robinson presentation</title>
   <abc>Sample other property</abc>
   <media:content url="https://s3.amazonaws.com/counterbalance-video/ool.m4v" />
</item>
```

The converted _json_ should also have property `abc`
```js
{
   /* . . . */
   "abc": "Sample other property"
   /* . . . */
}
```

**Comment by adrianwyard** [comment]
Hmmm, the JSON looks good but I see the following problem:
Using the test link above,
Click on the '>' button to see more playlist items,
The playlist items are not clickable, nor is the '<' button.
Any ideas?

**Comment by kayecandy** [comment]
> Hmmm, the JSON looks good but I see the following problem:
> Using the test link above,
> Click on the '>' button to see more playlist items,
> The playlist items are not clickable, nor is the '<' button.
> Any ideas?

Made a new issue (#21) for this

**Comment by adrianwyard** [comment]
The above is a separate issue. This one is fixed - and it's nice to have other properties come through too, such as thumbnail images if I were to add them.
