### ISSUE TITLE
Help needed with CSS for Related Items

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#19]
I was hoping to do this myself but I'm struggling:

The playlist UI has changed dramatically in version 8, now appearing as a 'Shelf Widget' below the video. I've added a new mediaWindowHtmlShelf() function that uses this: Here is an example: https://counterbalance.org/stars-ool/pres-frame.html

(Once the Title item is in the JSON you'll see that text below the items).

My playlists don't have thumbnails so I want to improve how the Shelf looks without them. Some ideas are:
+ Reduce the height of the thumbnail regions so they looks like buttons. Maybe 3:1 ratio, width:height.
+ Make them solid black or grey
+ Remove the janky transition at load time

Also change the font with:
	.jw-related-shelf { font-family: Verdana, Geneva, Tahoma, sans-serif; }

And remove the 'More videos' text with:
	.jw-related-more { visibility: hidden; }

Here's the doc:
https://developer.jwplayer.com/jwplayer/docs/jw8-css-skin-reference#discovery-overlay

Thanks.

**Comment by kayecandy** [comment]
Fixed this. Widget now looks like this:

![preview image](https://i.imgur.com/MAnYEnk.png)
