### ISSUE TITLE
CSS tied to just #myElement, not all players

### ISSUE THREAD

**Issue by adrianwyard** [adrianwyard/jwplayer-enhancements#20]
I noticed some styling is tied to #myElement so it doesn't affect players written with other div names - see cbfscript.js for these. Can we just make these style changes globally?

**Comment by adrianwyard** [comment]
Unique div names were introduced so more than one player can be on a page. The multi-player case seems to work OK now, so making styling global should be all we need to do.

**Comment by kayecandy** [comment]
Oh sorry about that. Fixed it now
