### ISSUE TITLE
Safari static properties for v14.1 below

### ISSUE THREAD

**Issue by kayecandy** [adrianwyard/jwplayer-enhancements#23]
_I'll just put this here for documentation purposes._

While I was testing #22, I found another possible bug for versions of Safari below v14.1 (I am current on V14.0.3 and so I came across this bug)

[Static class attributes are apparently not supported below v14.1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#browser_compatibility)

This shouldn't be much problem to refactor but I wanted to get your input if you would like to go ahead and refactor the code or should we detect the version of the browser and prompt for a version >= v.14.1?

I think refactoring is better, but of course this is up to you.

**Comment by adrianwyard** [comment]
Interesting. What are the effects? Unless severe I'm not a fan of prompts. Can #22 be fixed in 14.0.3 without finding a workaround for this? ...I'm happy for you to make your own judgment.

**Comment by adrianwyard** [comment]
Workaround is now completed?

**Comment by kayecandy** [comment]
Oh sorry I forgot to link it here. 

Yup! Here it is c215a50
